In [195]:
import numpy as np

a= np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [196]:
import time

weights = np.random.random(1000000)

inputs = np.random.random(1000000)

In [197]:
print(weights.shape)
print(inputs.shape)

(1000000,)
(1000000,)


## Vectorized Version

In [198]:
tic = time.time()

z= np.dot(weights,inputs)

toc= time.time()

print("Vectorized Version: "+ str(1000*(toc-tic))+"ms")

print("Z= "+str(z))

Vectorized Version: 11.04593276977539ms
Z= 249920.585897757


## Non-Vectorized Version

In [199]:
z=0

tic = time.time()

for i in range(len(inputs)):
    z += weights[i]*inputs[i]

toc= time.time()

print("Non-Vectorized Version: "+ str(1000*(toc-tic))+"ms")

print("Z= "+str(z))

Non-Vectorized Version: 930.0210475921631ms
Z= 249920.58589777275


# Example

In [200]:
v = np.array([2,4,6,8,9,10])
v.shape

(6,)

We want u = e^v

In [201]:
len(v)

6

## Non-vectorized

In [202]:
import math 

tic = time.time()

u = np.zeros((len(v),1))

for i in range(len(v)):
    u[i] = math.exp(v[i])
    
toc = time.time()

print("Non-Vectorized Version: "+ str(1000*(toc-tic))+" ms")

print(u)

Non-Vectorized Version: 0.2472400665283203 ms
[[7.38905610e+00]
 [5.45981500e+01]
 [4.03428793e+02]
 [2.98095799e+03]
 [8.10308393e+03]
 [2.20264658e+04]]


## Vectorized

In [203]:
import math 

tic = time.time()

u = np.exp(v)
    
toc = time.time()

print("Vectorized Version: "+ str(1000*(toc-tic))+" ms")

print(u)

Vectorized Version: 0.15687942504882812 ms
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


# Vectorizing Logistic Regression

In [204]:
inputs = np.array([[2,43,34,1,24]]) #Normal X values - Training examples

weights = np.array([[0.2,0.3,0.4,0.91,0.54]])

bias = np.array([2,4,6,12,43])

In [205]:
inputs.shape

(1, 5)

In [206]:
len(inputs)

1

In [207]:
weights.shape

(1, 5)

In [208]:
len(weights)

1

## Non-Vectorized

In [217]:
Z = np.zeros((5,5))

tic = time.time()

for i in range(len(weights[0])):
    for j in range(len(inputs[0])):
        Z[i][j]= (weights[0][i]*inputs[0][j])+bias[j]
    
toc = time.time()

print("Non-Vectorized Version: "+ str(1000*(toc-tic))+" ms")


print(Z)

Non-Vectorized Version: 2.0148754119873047 ms
[[ 2.4  12.6  12.8  12.2  47.8 ]
 [ 2.6  16.9  16.2  12.3  50.2 ]
 [ 2.8  21.2  19.6  12.4  52.6 ]
 [ 3.82 43.13 36.94 12.91 64.84]
 [ 3.08 27.22 24.36 12.54 55.96]]


In [218]:
Z = np.zeros((len(bias)))
Z.shape

(5,)

In [219]:
Z[4]

0.0

## Vectorized

In [212]:
tic = time.time()

Z= (np.dot(weights.T,inputs))+bias #Multiply will multiply all numbers in a array
    
toc = time.time()

print("Vectorized Version: "+ str(1000*(toc-tic))+" ms")

print(Z)

Vectorized Version: 3.7276744842529297 ms
[[ 2.4  12.6  12.8  12.2  47.8 ]
 [ 2.6  16.9  16.2  12.3  50.2 ]
 [ 2.8  21.2  19.6  12.4  52.6 ]
 [ 3.82 43.13 36.94 12.91 64.84]
 [ 3.08 27.22 24.36 12.54 55.96]]


In [213]:
type(Z)

numpy.ndarray

## Example

In [214]:
# Number of features
n = 1000
# Number of training examples
m = 10000
# Initialize X and W
X = np.random.rand(n,m)
W = np.random.rand(n,1)

In [215]:
X.shape

(1000, 10000)

In [216]:
W.shape

(1000, 1)

## Vectorizing Logistic Regression's Gradient Output

In [92]:
t=[[1,2],[2,8],[9,14],[15,18]]

In [93]:
list(range(len(t)))

[0, 1, 2, 3]

In [94]:
t[3][0]

15

In [95]:
len(t)

4

In [96]:
c=[]
for i in list(range(len(t))):
    if t[i][0] <= t[i][1]:
        if i!=len(t)-1:
            if t[i][1]==t[i+1][0] or t[i+1][0]<t[i][1]:
                c.append([t[i][0],t[i+1][1]])
            else:
                c.append([t[i][0],t[i][1]])
        else:
            c.append([t[i][0],t[i][1]])
    

In [98]:
c

[[1, 8], [2, 8], [9, 14], [15, 18]]

In [99]:
len(c)

4

In [103]:
for i in range(len(c)):
    if i<len(c)-1:
        if c[i][1]==c[i+1][1]:
            del c[i+1]

In [104]:
c

[[1, 8], [9, 14], [15, 18]]

## Basit Hata

In [192]:
words=["daire", "darie", "temiz", "temzi", "doktordan", "doktordna", "satilik", "sat"]

In [193]:
def basitHata(words):
    dic_lst=[]
    
    for word in words:
        dic={}
        for i in set(word):
              dic[i]=word.count(i)
        dic_lst.append(dic)
    mainlst=[]
    sublst=[]
    cpy=dic_lst.copy()
    for dic in dic_lst:
        if dic in cpy:
            c=dic_lst.count(dic)
            sublst=[]
            bef=-1
            for _ in range(c):
                index=(dic_lst[bef+1:].index(dic))+bef+1
                bef=index
                sublst.append(words[index])
        mainlst.append(sublst)
    return mainlst

In [194]:
basitHata(words)

[['daire', 'darie'],
 ['daire', 'darie'],
 ['temiz', 'temzi'],
 ['temiz', 'temzi'],
 ['doktordan', 'doktordna'],
 ['doktordan', 'doktordna'],
 ['satilik'],
 ['sat']]

In [187]:
s=set(words)
s

{'daire',
 'darie',
 'doktordan',
 'doktordna',
 'sat',
 'satilik',
 'temiz',
 'temzi'}

In [188]:
for i in words:
    words.remove(i)
    for j in s:
        if len(i)==len(j):
            li.append([])

In [189]:
li

[[], [], [], [], [], [], [], [], [], [], []]

In [148]:
for i in words:
    l=len(i)
    k=i
    words.remove(i)
    y=words
    for j in y:
        if l == len(j):
            li.append([k,j])
            words.remove(j)
        else:
            li.append([j])

In [149]:
li

[['daire', 'darie'],
 ['daire', 'temzi'],
 ['doktordna'],
 ['satilik'],
 ['sat'],
 ['temiz'],
 ['doktordan', 'doktordna'],
 ['sat'],
 ['temiz'],
 ['satilik']]